#!/bin/bash
#PBS -N Evaluate
#PBS -l walltime=04:00:00
#PBS -q v1_medium24
#PBS -l select=1:ncpus=1:mem=128gb
#PBS -o evaluate.out
#PBS -e evaluate.err
#PBS -V

cd $PBS_O_WORKDIR

source ~/.bashrc
conda activate irp-env

python results/loss/metric_evaluate.py \
    --dataset cylinder \
    --model_configs \
        "DMD:DMD:none" \
        "CAE-Jointly:CAE_LinearMLP:results/checkpoints/CAE_MLP/cylinder_CAE_LinearMLP_jointly_large_epoch" \
        "CAE-Multiply:CAE_LinearMLP:results/checkpoints/CAE_MLP/cylinder_CAE_LinearMLP_multiply_large_epoch" \
        "CAE-Separately:CAE_LinearMLP:results/checkpoints/CAE_MLP/cylinder_CAE_LinearMLP_separately_large_epoch" \
        "CAEW-Jointly:CAE_WeakLinearMLP:results/checkpoints/CAE_MLP/cylinder_CAE_WeakLinearMLP_jointly_large_epoch" \
        "CAEW-Multiply:CAE_WeakLinearMLP:results/checkpoints/CAE_MLP/cylinder_CAE_WeakLinearMLP_multiply_large_epoch" \
        "CAEW-Separately:CAE_WeakLinearMLP:results/checkpoints/CAE_MLP/cylinder_CAE_WeakLinearMLP_separately_large_epoch" \
    --data_path ./data \
    --dmd_rank 50 \
    --output_path ./results/loss/comparison_cylinder.csv