#!/bin/bash
#PBS -N GPU-test
#PBS -l walltime=16:00:00
#PBS -q v1_medium24
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -o debug-gpu.out
#PBS -e debug-gpu.err
#PBS -V

cd $PBS_O_WORKDIR

source ~/.bashrc
conda activate irp-env

# module load tools/prod
# module load matplotlib
# module load PyYAML
# module load SciPy-bundle
# module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1

python src/main.py --model CAE_WeakLinearMLP --dataset kolmogorov --config configs/CAE_MLP.yaml

# python src/gpu-test.py