#!/bin/bash
#PBS -N Plot
#PBS -l walltime=00:10:00
#PBS -q v1_medium24
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -o plot.out
#PBS -e plot.err
#PBS -V

cd $PBS_O_WORKDIR

source ~/.bashrc
conda activate irp-env

python results/plots/comparison.py \
    --dataset cylinder \
    --model_type CAE_LinearMLP \
    --jointly_path ./results/checkpoints/CAE_MLP/cylinder_CAE_LinearMLP_jointly_large_epoch \
    --separately_path ./results/checkpoints/CAE_MLP/cylinder_CAE_LinearMLP_separately_large_epoch \
    --multiply_path ./results/checkpoints/CAE_MLP/cylinder_CAE_LinearMLP_multiply_large_epoch \
    --sample_idx 5 \
    --prediction_steps 1000 \
    --save_path ./results/plots/cylinder_linear_comparison.png